# Generated by Django 4.2.7 on 2023-12-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='wastage',
        ),
    ]
