# Generated by Django 4.2.3 on 2023-12-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bom',
            new_name='BomProduct',
        ),
        migrations.CreateModel(
            name='BomMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bomproduct')),
            ],
        ),
    ]
