# Generated by Django 4.2.3 on 2023-12-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_bom_bomproduct_bommaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bommaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.material'),
        ),
    ]
